// Caminho: app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Usando a fonte padrão "Inter"
import "./globals.css"; // A linha que importa o Tailwind

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ConectaEdu", // O seu título
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // As tags <html> e <body> corretas
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}